Set TINS_HAVE_CXX11 to 1 (#3350)
Modified to use the CXX11 Compiler.

```
The command fails with:
[3734/3989] Compiling C++ object src/upf/libarp_nd.a.p/arp-nd.cpp.o
ninja: build stopped: subcommand failed.

The error lines are:
[3730/3989] Compiling C++ object subprojects/libtins/src/libtins.so.4.3.p/utils_resolve_utils.cpp.o
FAILED: subprojects/libtins/src/libtins.so.4.3.p/utils_resolve_utils.cpp.o
c++ -Isubprojects/libtins/src/libtins.so.4.3.p -Isubprojects/libtins/src -I../subprojects/libtins/src -Isubprojects/libtins/include -I../subprojects/libtins/include -fdiagnostics-color=always -D_LIBCPP_HARDENING_MODE=_LIBCPP_HARDENING_MODE_FAST -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -O0 -g -Werror -Wno-deprecated-declarations -Wno-unused-private-field -fPIC -MD -MQ subprojects/libtins/src/libtins.so.4.3.p/utils_resolve_utils.cpp.o -MF subprojects/libtins/src/libtins.so.4.3.p/utils_resolve_utils.cpp.o.d -o subprojects/libtins/src/libtins.so.4.3.p/utils_resolve_utils.cpp.o -c ../subprojects/libtins/src/utils/resolve_utils.cpp
In file included from ../subprojects/libtins/src/utils/resolve_utils.cpp:59:
../subprojects/libtins/include/tins/detail/smart_ptr.h:44:18: error: no template named 'auto_ptr' in namespace 'std'
44 | typedef std::auto_ptr type;
| ~~~~~^
../subprojects/libtins/src/utils/resolve_utils.cpp:116:13: error: use of undeclared identifier 'response'
116 | if (response.get()) {
| ^
../subprojects/libtins/src/utils/resolve_utils.cpp:117:35: error: use of undeclared identifier 'response'
117 | const ARP* arp_resp = response->find_pdu();
```